# Site settings
baseurl = "http://twofliesinoneclap.com/"
languageCode = "en-gb"
title = "Two Flies in One Clap"
theme = "hugo-cactus-theme"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = ""

[params]
	name = "Two Flies in One Clap"
	description = "The Two Birds in One Stone alternative."
	bio = "Three geeks blogging about their daily beez neez."
	# Enter optionally your twitter account
	twitter = ""
	enableRSS = true

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = ""
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

    # Social icons style - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/"
    facebook = "https://www.facebook.com/"
    github   = "https://www.github.com/"
    dribble  = "https://www.dribbble.com/"

