twofliesinoneclap_com:
  build: .
  command: >
    server --baseURL="http://twofliesinoneclap.com"
           --destination="/tmp/site"
           --bind=0.0.0.0
           --port=80
           --watch
           --verbose
  ports:
    - "80:80"
  volumes:
    - .:/www
  restart: always
pull_hook:
  build: hook/
  ports:
    - "9001:9001"
  volumes:
    - .:/data
